name: Upload to DAFNI

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    name: Upload to DAFNI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build . -t pyramid-prepare-data:latest -f Dockerfile

      - name: Compress docker image
        run: docker save pyramid-prepare-data:latest | gzip > pyramid-prepare-data.tar.gz

      - name: Set tag as env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Verify release version tag
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Upload to DAFNI
        uses: dafnifacility/dafni-model-uploader@v1.11
        with:
          definition-path: './model-definition.yaml'
          image-path: './pyramid-prepare-data.tar.gz'
          username: ${{ secrets.DAFNI_SERVICE_ACCOUNT_USERNAME }}
          password: ${{ secrets.DAFNI_SERVICE_ACCOUNT_PASSWORD }}
          version-message: ${{ env.RELEASE_VERSION }}
          parent-model: "a51af454-4501-4ae8-bfee-8a4ece535671"
